settings:
  jira_project_key: "TAP"
  status_mapping:
    opened: Untriaged
    closed: done
    not_planned: rejected

  components:
    - parca-agent
    - team-tracing

  add_gh_comment: false
  sync_description: false
  sync_comments: false

  label_mapping:
    "Type: Enhancement": Story