debug_info:
  bucket:
    type: "FILESYSTEM"
    config:
      directory: "./tmp"
  cache:
    type: "FILESYSTEM"
    config:
      directory: "./tmp"

scrape_configs:
  - job_name: "parca"
    scrape_interval: "2s"
    static_configs:
      - targets: ["127.0.0.1:7070"]
  - job_name: "juju"
    scrape_interval: "2s"
    static_configs:
      - targets: ["127.0.0.1:6000"]
