object_storage:
  bucket:
    type: "FILESYSTEM"
    config:
      directory: "/var/lib/parca"

scrape_configs:
  - job_name: "juju"
    scrape_interval: "{{ interval }}s"
    static_configs:
      - targets: ["127.0.0.1:6000"]
  # Job to profile parca itself - disabled for now
  # - job_name: "parca"
  #   scrape_interval: "2s"
  #   static_configs:
  #     - targets: ["127.0.0.1:7070"]
