name: Build/Test

on:
  workflow_call:
    secrets:
      CHARMHUB_TOKEN:
        required: true

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4
      - name: Install dependencies
        run: python3 -m pip install tox
      - name: Run linters
        run: tox -e lint

  unit-test:
    name: Unit tests
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4
      - name: Install dependencies
        run: python -m pip install tox
      - name: Run tests
        run: tox -e unit

  lib-check:
    name: Check libraries
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4
        with:
          fetch-depth: 0
      - name: Check libs
        uses: canonical/charming-actions/check-libraries@46fe0c6d63324b5f74ce0e65d6ab47051953cc48 # 2.6.2
        with:
          credentials: "${{ secrets.CHARMHUB_TOKEN }}"
          github-token: "${{ secrets.GITHUB_TOKEN }}"

  functional-test:
    name: Functional tests
    runs-on: ubuntu-latest
    needs:
      - lib-check
      - unit-test
      - lint
    steps:
      - name: Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4
      - name: Install dependencies
        run: python -m pip install tox
      - name: Setup LXD
        uses: canonical/setup-lxd@8fb85546a934dfb994becf81341dd387ffe6aabb
      - name: Run tests
        run: tox -e functional

  integration-test:
    name: Integration tests (lxd)
    runs-on: ubuntu-22.04
    needs:
      - lib-check
      - unit-test
      - lint
    steps:
      - name: Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4
      - name: Setup operator environment
        uses: charmed-kubernetes/actions-operator@main
        with:
          provider: lxd
          juju-channel: 3.5/stable
      - name: Run integration tests
        run: tox -e integration
