name: Pull Requests
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - "renovate/**"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  pull-request:
    name: PR
    uses: canonical/observability/.github/workflows/charm-pull-request.yaml@main
    secrets: inherit
    with:
      provider: lxd