name: Release to latest/edge

on:
  push:
    branches:
      - main
    paths-ignore:
      - ".github/renovate*"
      - ".github/workflows/release.yaml"
      - ".github/workflows/renovate.yaml"
      - ".github/workflows/update-libs.yaml"
      - ".gitignore"
      - "tox.ini"

jobs:
  test:
    uses: ./.github/workflows/build-and-test.yaml
    secrets:
      CHARMHUB_TOKEN: "${{ secrets.CHARMHUB_TOKEN }}"

  release-to-charmhub:
    name: Release to CharmHub
    needs:
      - test
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4
        with:
          fetch-depth: 0
      - name: Select charmhub channel
        uses: canonical/charming-actions/channel@33627add534483f7d5bd83fff736a9330db3b4f8 # 2.6.0
        id: channel
      - name: Upload charm to charmhub
        uses: canonical/charming-actions/upload-charm@33627add534483f7d5bd83fff736a9330db3b4f8 # 2.6.0
        with:
          credentials: "${{ secrets.CHARMHUB_TOKEN }}"
          github-token: "${{ secrets.GITHUB_TOKEN }}"
          channel: "${{ steps.channel.outputs.name }}"
