# workflow for checking package versions and opening PRs to bump
name: Renovate
on:
  schedule:
    - cron: "0 12 * * *"
  workflow_dispatch:
  workflow_call:

jobs:
  renovate:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # v3.1.0

      - name: Self-hosted Renovate
        uses: renovatebot/github-action@0546b792f88eec7340ea2faf6a6c5e966e1e3ea6 # v34.39.0
        with:
          configurationFile: .github/renovate-config.js
          token: ${{ github.token }}
