# workflow for checking package versions and opening PRs to bump
name: Renovate
on:
  schedule:
    - cron: "0 12 * * *"
  workflow_dispatch:
  workflow_call:

jobs:
  renovate:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3.3.0

      - name: Self-hosted Renovate
        uses: renovatebot/github-action@1c6288ccd6c960b99957a5e1bdb0ea9fc992d35f # v34.152.0
        with:
          configurationFile: .github/renovate-config.js
          token: ${{ github.token }}
