# workflow for checking package versions and opening PRs to bump
name: Renovate
on:
  schedule:
    - cron: "0 12 * * *"
  workflow_dispatch:
  workflow_call:

jobs:
  renovate:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3.3.0

      - name: Self-hosted Renovate
        uses: renovatebot/github-action@33fce9286b85fbc0be2a9a18f03db7e0acf3bfa1 # v34.77.1
        with:
          configurationFile: .github/renovate-config.js
          token: ${{ github.token }}
